web: ./start.sh uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}
worker: ./start.sh python -m celery -A core.celery_app worker --pool=prefork --concurrency=${CELERY_WORKER_CONCURRENCY:-8} --loglevel=info -Q celery,queues.parsing,queues.embedding,queues.indexing
